from typing import Any, Iterable, Union

proj_version_str: str

class Proj:
    srs: str
    def __init__(self, proj_string: str) -> None: ...
    @property
    def definition(self) -> str: ...
    @property
    def has_inverse(self) -> bool: ...
    def _fwd(
        self,
        lons: Union[Iterable[float], float],
        lats: Union[Iterable[float], float],
        errcheck: bool = False,
    ) -> None: ...
    def _inv(
        self,
        x: Union[Iterable[float], float],
        y: Union[Iterable[float], float],
        errcheck: bool = False,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def _is_equivalent(self, other: Proj) -> bool: ...
    def is_exact_same(self, other: Any) -> bool: ...
