from array import array
from typing import Any, Iterable, List, Tuple, Union

AnyArrayOrScalar = Union[Iterable, List, Tuple, float, int, array]
proj_version_str: str

class Proj:
    srs: str
    def __init__(self, proj_string: str) -> None: ...
    @property
    def definition(self) -> str: ...
    @property
    def has_inverse(self) -> bool: ...
    def _fwd(
        self, lons: AnyArrayOrScalar, lats: AnyArrayOrScalar, errcheck: bool = False
    ) -> AnyArrayOrScalar: ...
    def _inv(
        self, x: AnyArrayOrScalar, y: AnyArrayOrScalar, errcheck: bool = False
    ) -> AnyArrayOrScalar: ...
    def __repr__(self) -> str: ...
    def _is_equivalent(self, other: Proj) -> bool: ...
    def is_exact_same(self, other: Any) -> bool: ...
