from typing import Any

proj_version_str: str

class Proj:
    srs: str
    def __init__(self, proj_string: str) -> None: ...
    @property
    def definition(self) -> str: ...
    @property
    def has_inverse(self) -> bool: ...
    def _fwd(self, lons: Any, lats: Any, errcheck: bool = False) -> None: ...
    def _inv(self, x: Any, y: Any, errcheck: bool = False) -> None: ...
    def __repr__(self) -> str: ...
    def _is_equivalent(self, other: Proj) -> bool: ...
    def is_exact_same(self, other: Any) -> bool: ...
